services:

  _defaults:
    autowire: true
    autoconfigure: true

  Symfony\Component\PropertyAccess\PropertyAccessorInterface:
    class: Symfony\Component\PropertyAccess\PropertyAccessor

  log_handler:
    autowire: true
    class: Symfony\Bridge\Monolog\Handler\ConsoleHandler

  Psr\Log\LoggerInterface:
    autowire: false
    class: Monolog\Logger
    arguments:
      - "log"
      - ["@log_handler"]

  logger:
    alias: Psr\Log\LoggerInterface

  Palmyr\Console\EventListener\DebugHandlerListener:
    class: Palmyr\Console\EventListener\DebugHandlerListener
    arguments:
      - '@error_handler'
      - '@Psr\Log\LoggerInterface'

  event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher
    public: true

  Symfony\Component\Filesystem\Filesystem: {}
