services:

  _defaults:
    autowire: true
    autoconfigure: true

  Symfony\Component\PropertyAccess\PropertyAccessorInterface:
    class: Symfony\Component\PropertyAccess\PropertyAccessor

  log_handler:
    class: Symfony\Bridge\Monolog\Handler\ConsoleHandler
    arguments:
      - "php://stdout"

  Psr\Log\LoggerInterface:
    autowire: false
    class: Monolog\Logger
    arguments:
      - "log"
      - ["@log_handler"]

  logger:
    alias: Psr\Log\LoggerInterface